"""first revision

Revision ID: bbb63b1f8f61
Revises: 
Create Date: 2021-09-25 22:53:24.176707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb63b1f8f61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lectures',
                    sa.Column('entry_id', sa.Integer(), nullable=False),
                    sa.Column('sede', sa.String(), nullable=True),
                    sa.Column('aula', sa.String(), nullable=True),
                    sa.Column('data_lezione', sa.String(), nullable=True),
                    sa.Column('ora_inizio', sa.String(), nullable=True),
                    sa.Column('ora_fine', sa.String(), nullable=True),
                    sa.Column('qr', sa.String(), nullable=True),
                    sa.Column('nome', sa.String(), nullable=True),
                    sa.Column('ora_inizio_lezione',
                              sa.String(), nullable=True),
                    sa.Column('ora_fine_lezione', sa.String(), nullable=True),
                    sa.Column('lecture_timestamp',
                              sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('entry_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lectures')
    # ### end Alembic commands ###
